### ISSUE TITLE
Data and API versioning

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr.org#214]
I began to version the specification in https://github.com/tosdr/tosdr.org/wiki/ and I added spec-version in the json files. However, there were differences between some points so I did not add the spec-version to all points/*json -- this should be fixed if the files are correctly using the spec https://github.com/tosdr/tosdr.org/wiki/Specification:-points

**TODO**
- [ ] apply the spec-version according to the specification to remaining points in `src/points/`
- [ ] add the spec-version information for forms submit-point.html etc.
- [ ] we created new files for comments, etc. Please also document the data format and version it cc @michielbdejong
