### ISSUE TITLE
API: give list of rated services

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr.org#215]
I suppose that the API should also offer something
like: https://tosdr.org/api/1/ratings.json

for the list of services that are in the database, with their
    associated Class (A-E or no Class) and their URL.

That way the browser extension only needs to download ratings.json
at every startup to get up-to-date data (instead of relying on https://tosdr.org/index/services.json for instance -- which should be deprecated)

**TODO**
- [x] write the code for the API
- [ ] update the https://github.com/tosdr/browser-extensions
- [ ] document it in `src/api.html`
